2024-11-05 10:43:55,955 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:43:59,398 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:43:59,528 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\AppData\Local\Programs\Python\Python311\Lib\contextlib.py:155: UserWarning:

Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
2024-11-05 10:43:59,535 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\callbacks\early_stopping.py:155: UserWarning:

Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae,mse
2024-11-05 10:45:05,889 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:45:06,187 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:49:55,034 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:49:59,197 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:49:59,328 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\AppData\Local\Programs\Python\Python311\Lib\contextlib.py:155: UserWarning:

Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
2024-11-05 10:49:59,334 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\callbacks\early_stopping.py:155: UserWarning:

Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae,mse
2024-11-05 10:49:59,419 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc Traceback (most recent call last):
2024-11-05 10:49:59,421 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
2024-11-05 10:49:59,421 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 265, in _run_and_update_trial
    tuner_utils.convert_to_metrics_dict(
2024-11-05 10:49:59,422 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in convert_to_metrics_dict
    [convert_to_metrics_dict(elem, objective) for elem in results]
2024-11-05 10:49:59,423 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in <listcomp>
    [convert_to_metrics_dict(elem, objective) for elem in results]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-05 10:49:59,423 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 145, in convert_to_metrics_dict
    best_value, _ = _get_best_value_and_best_epoch_from_history(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-05 10:49:59,424 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 116, in _get_best_value_and_best_epoch_from_history
    objective_value = objective.get_value(metrics)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-05 10:49:59,424 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc File "C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras_tuner\src\engine\objective.py", line 59, in get_value
    return logs[self.name]
           ~~~~^^^^^^^^^^^
2024-11-05 10:49:59,425 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc KeyError: 'val_loss'
2024-11-05 10:49:59,744 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning:

Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
2024-11-05 10:49:59,870 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:50:03,952 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:50:04,086 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\AppData\Local\Programs\Python\Python311\Lib\contextlib.py:155: UserWarning:

Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
2024-11-05 10:50:04,092 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\callbacks\early_stopping.py:155: UserWarning:

Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae,mse
2024-11-05 10:50:04,184 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
2024-11-05 10:50:04,518 - ERROR - 3231ebec-af60-4d30-9ad0-055c7c6c99cc C:\Users\daniel.woodrich\Work\Data mgmt coord\Projects\irina cloud\ml_app\venv2\Lib\site-packages\keras\src\models\functional.py:225: UserWarning:

The structure of `inputs` doesn't match the expected structure: ['keras_tensor', 'keras_tensor_1']. Received: the structure of inputs=('*', '*')
